---
swagger: '2.0'
info:
  title: To-dos
  version: '1.0'
  description: |-
    Exampe of loads of examples, some right, some wrong.
  contact:
    name: Stoplight
    url: https://stoplight.io
  license:
    name: MIT
host: example.org
schemes:
- http
consumes:
- application/json
produces:
- application/json
tags: 
  - media-examples
  - schema-examples
paths:

  "/response-examples":
    get:
      operationId: response-examples-inline
      description: when examples are inline (no $ref involved)
      tags: 
        - media-examples
      responses:
        '200':
          description: 'Success, because the example matches the schema'
          schema:
            properties: 
              id:
                type: integer
              name:
                type: string
              completed: 
                type: boolean
              completed_at:
                type: string,
                nullable: true
                format: date-time
            required:
              - id
              - name
              - completed
          example:
            application/json:
              id: 1
              name: get food
              completed: false
              completed_at: '1955-04-23T13:22:52.685Z'
        '500':
          description: 'Fail, because the example is nonsense'
          schema:
            properties: 
              id:
                type: integer
              name:
                type: string
              completed: 
                type: boolean
              completed_at:
                type: string,
                nullable: true
                format: date-time
            required:
              - id
              - name
              - completed
          examples:
            application/json:
              id: 1
              completed: Not a boolean
              completed_at: 'Not a date'
  

  "/response-examples-via-$ref":
    get:
      operationId: response-examples-via-$ref
      description: When the example is compared against a schema that ia a $ref to another file
      tags: 
        - media-examples
      responses:
        '200':
          description: 'Success, because the example matches the definition in a $ref'
          schema:
            "$ref": "./models/todo-full.v1.json"
          examples:
            application/json:
              id: 1
              name: get food
              completed: false
              completed_at: '1955-04-23T13:22:52.685Z'
              created_at: '1994-11-05T03:26:51.471Z'
              updated_at: '1989-07-29T11:30:06.701Z'
  